"""initial_schema

Revision ID: 86747e91948b
Revises: 
Create Date: 2026-09-03 16:53:33.910595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86747e91948b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.TEXT(),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.drop_index(op.f('idx_api_keys_hash'), table_name='api_keys', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_api_keys_org'), table_name='api_keys')
    op.drop_column('api_keys', 'name')
    op.drop_column('api_keys', 'revoked_at')
    op.drop_column('api_keys', 'last_used_at')
    op.add_column('audit_logs', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('audit_logs', 'actor_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('idx_audit_logs_org'), table_name='audit_logs')
    op.drop_column('audit_logs', 'metadata')
    op.alter_column('events', 'api_key_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('events', 'idempotency_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('events', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('events', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'received'::text"))
    op.drop_constraint(op.f('events_organization_id_idempotency_key_key'), 'events', type_='unique')
    op.drop_index(op.f('idx_events_org_type'), table_name='events')
    op.drop_index(op.f('idx_events_received_at'), table_name='events')
    op.drop_index(op.f('idx_events_status'), table_name='events')
    op.create_unique_constraint('uq_events_org_idempotency', 'events', ['organization_id', 'idempotency_key'])
    op.drop_constraint(op.f('events_api_key_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'api_keys', ['api_key_id'], ['id'])
    op.drop_column('events', 'processed_at')
    op.alter_column('organizations', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('organizations', 'updated_at')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'member'::text"))
    op.drop_index(op.f('idx_users_org'), table_name='users')
    op.add_column('webhook_deliveries', sa.Column('error_detail', sa.Text(), nullable=True))
    op.alter_column('webhook_deliveries', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_index(op.f('idx_webhook_deliveries_event'), table_name='webhook_deliveries')
    op.drop_index(op.f('idx_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_column('webhook_deliveries', 'response_body_snippet')
    op.alter_column('webhook_endpoints', 'secret',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('idx_webhook_endpoints_org'), table_name='webhook_endpoints')
    op.drop_column('webhook_endpoints', 'event_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_endpoints', sa.Column('event_types', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_webhook_endpoints_org'), 'webhook_endpoints', ['organization_id'], unique=False)
    op.alter_column('webhook_endpoints', 'secret',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('webhook_deliveries', sa.Column('response_body_snippet', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_webhook_deliveries_status'), 'webhook_deliveries', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('idx_webhook_deliveries_event'), 'webhook_deliveries', ['event_id'], unique=False)
    op.alter_column('webhook_deliveries', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_column('webhook_deliveries', 'error_detail')
    op.create_index(op.f('idx_users_org'), 'users', ['organization_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'member'::text"))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('organizations', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('organizations', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('events', sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_api_key_id_fkey'), 'events', 'api_keys', ['api_key_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_events_org_idempotency', 'events', type_='unique')
    op.create_index(op.f('idx_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('idx_events_received_at'), 'events', ['received_at'], unique=False)
    op.create_index(op.f('idx_events_org_type'), 'events', ['organization_id', 'event_type'], unique=False)
    op.create_unique_constraint(op.f('events_organization_id_idempotency_key_key'), 'events', ['organization_id', 'idempotency_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('events', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'received'::text"))
    op.alter_column('events', 'event_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('events', 'idempotency_key',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('events', 'api_key_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_audit_logs_org'), 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'actor_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('audit_logs', 'extra')
    op.add_column('api_keys', sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('api_keys', sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('api_keys', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_api_keys_org'), 'api_keys', ['organization_id'], unique=False)
    op.create_index(op.f('idx_api_keys_hash'), 'api_keys', ['key_hash'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.String(length=8),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
